### ISSUE TITLE
[JENKINS-73915] requested location il-central-1, which is not in the configured locations

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/artifact-manager-s3-plugin#758]
<p>When using a bucket in `il-central-1`, I see</p>

<pre>
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 56935aa0-1173-4463-9c8a-a8b2c55cf7d7
java.lang.IllegalArgumentException: requested location il-central-1, which is not in the configured locations: {us-standard=Suppliers.ofInstance(https:<span class="code-comment">//s3.amazonaws.com), us-east-2=Suppliers.ofInstance(https://s3-us-east-2.amazonaws.com), us-west-1=Suppliers.ofInstance(https://s3-us-west-1.amazonaws.com), us-west-2=Suppliers.ofInstance(https://s3-us-west-2.amazonaws.com), ca-central-1=Suppliers.ofInstance(https://s3-ca-central-1.amazonaws.com), eu-west-1=Suppliers.ofInstance(https://s3-eu-west-1.amazonaws.com), eu-west-2=Suppliers.ofInstance(https://s3-eu-west-2.amazonaws.com), eu-west-3=Suppliers.ofInstance(https://s3-eu-west-3.amazonaws.com), eu-central-1=Suppliers.ofInstance(https://s3-eu-central-1.amazonaws.com), eu-north-1=Suppliers.ofInstance(https://s3-eu-north-1.amazonaws.com), sa-east-1=Suppliers.ofInstance(https://s3-sa-east-1.amazonaws.com), ap-southeast-1=Suppliers.ofInstance(https://s3-ap-southeast-1.amazonaws.com), ap-southeast-2=Suppliers.ofInstance(https://s3-ap-southeast-2.amazonaws.com), ap-south-1=Suppliers.ofInstance(https://s3-ap-south-1.amazonaws.com), ap-northeast-1=Suppliers.ofInstance(https://s3-ap-northeast-1.amazonaws.com), ap-northeast-2=Suppliers.ofInstance(https://s3-ap-northeast-2.amazonaws.com), cn-north-1=Suppliers.ofInstance(https://s3.cn-north-1.amazonaws.com.cn), cn-northwest-1=Suppliers.ofInstance(https://s3.cn-north-s3.cn-northwest-1.amazonaws.com.cn), me-south-1=Suppliers.ofInstance(https://s3.me-south-1.amazonaws.com)}
</span>	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:448)
	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.location.functions.RegionToEndpointOrProviderIfNull.apply(RegionToEndpointOrProviderIfNull.java:60)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.s3.functions.AssignCorrectHostnameForBucket.apply(AssignCorrectHostnameForBucket.java:46)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.s3.functions.AssignCorrectHostnameForBucket.apply(AssignCorrectHostnameForBucket.java:29)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.RestAnnotationProcessor.getEndpointInParametersOrNull(RestAnnotationProcessor.java:528)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.RestAnnotationProcessor.getEndpointFor(RestAnnotationProcessor.java:551)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.RestAnnotationProcessor.apply(RestAnnotationProcessor.java:204)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.RestAnnotationProcessor.apply(RestAnnotationProcessor.java:137)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.InvokeHttpMethod.toCommand(InvokeHttpMethod.java:189)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:85)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3/jdk.proxy94/jdk.proxy94.$Proxy220.listBucket(Unknown Source)
	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.s3.blobstore.S3BlobStore.list(S3BlobStore.java:177)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//io.jenkins.plugins.artifact_manager_jclouds.JCloudsVirtualFile.isDirectory(JCloudsVirtualFile.java:172)
</span>	at PluginClassLoader <span class="code-keyword">for</span> copyartifact<span class="code-comment">//hudson.plugins.copyartifact.BuildSelector.getArtifacts(BuildSelector.java:131)
</span>	at PluginClassLoader <span class="code-keyword">for</span> copyartifact<span class="code-comment">//hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:673)
</span>	at PluginClassLoader <span class="code-keyword">for</span> copyartifact<span class="code-comment">//hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:563)
</span>	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at PluginClassLoader <span class="code-keyword">for</span> workflow-basic-steps<span class="code-comment">//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
</span>	at PluginClassLoader <span class="code-keyword">for</span> workflow-basic-steps<span class="code-comment">//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
</span>	at PluginClassLoader <span class="code-keyword">for</span> workflow-step-api<span class="code-comment">//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
</span>	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:840) </pre>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/veertunathan.png" title="veertunathan's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=veertunathan">veertunathan</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-73915" target="_blank">requested location il-central-1, which is not in the configured locations</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: artifact-manager-s3-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-12-02
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>When using a bucket in `il-central-1`, I see</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 56935aa0-1173-4463-9c8a-a8b2c55cf7d7
java.lang.IllegalArgumentException: requested location il-central-1, which is not in the configured locations: {us-standard=Suppliers.ofInstance(https:<span class="code-comment">//s3.amazonaws.com), us-east-2=Suppliers.ofInstance(https://s3-us-east-2.amazonaws.com), us-west-1=Suppliers.ofInstance(https://s3-us-west-1.amazonaws.com), us-west-2=Suppliers.ofInstance(https://s3-us-west-2.amazonaws.com), ca-central-1=Suppliers.ofInstance(https://s3-ca-central-1.amazonaws.com), eu-west-1=Suppliers.ofInstance(https://s3-eu-west-1.amazonaws.com), eu-west-2=Suppliers.ofInstance(https://s3-eu-west-2.amazonaws.com), eu-west-3=Suppliers.ofInstance(https://s3-eu-west-3.amazonaws.com), eu-central-1=Suppliers.ofInstance(https://s3-eu-central-1.amazonaws.com), eu-north-1=Suppliers.ofInstance(https://s3-eu-north-1.amazonaws.com), sa-east-1=Suppliers.ofInstance(https://s3-sa-east-1.amazonaws.com), ap-southeast-1=Suppliers.ofInstance(https://s3-ap-southeast-1.amazonaws.com), ap-southeast-2=Suppliers.ofInstance(https://s3-ap-southeast-2.amazonaws.com), ap-south-1=Suppliers.ofInstance(https://s3-ap-south-1.amazonaws.com), ap-northeast-1=Suppliers.ofInstance(https://s3-ap-northeast-1.amazonaws.com), ap-northeast-2=Suppliers.ofInstance(https://s3-ap-northeast-2.amazonaws.com), cn-north-1=Suppliers.ofInstance(https://s3.cn-north-1.amazonaws.com.cn), cn-northwest-1=Suppliers.ofInstance(https://s3.cn-north-s3.cn-northwest-1.amazonaws.com.cn), me-south-1=Suppliers.ofInstance(https://s3.me-south-1.amazonaws.com)}
</span>	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:448)
	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.location.functions.RegionToEndpointOrProviderIfNull.apply(RegionToEndpointOrProviderIfNull.java:60)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.s3.functions.AssignCorrectHostnameForBucket.apply(AssignCorrectHostnameForBucket.java:46)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.s3.functions.AssignCorrectHostnameForBucket.apply(AssignCorrectHostnameForBucket.java:29)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.RestAnnotationProcessor.getEndpointInParametersOrNull(RestAnnotationProcessor.java:528)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.RestAnnotationProcessor.getEndpointFor(RestAnnotationProcessor.java:551)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.RestAnnotationProcessor.apply(RestAnnotationProcessor.java:204)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.RestAnnotationProcessor.apply(RestAnnotationProcessor.java:137)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.InvokeHttpMethod.toCommand(InvokeHttpMethod.java:189)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:85)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.<span class="code-keyword">rest</span>.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3/jdk.proxy94/jdk.proxy94.$Proxy220.listBucket(Unknown Source)
	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//org.jclouds.s3.blobstore.S3BlobStore.list(S3BlobStore.java:177)
</span>	at PluginClassLoader <span class="code-keyword">for</span> artifact-manager-s3<span class="code-comment">//io.jenkins.plugins.artifact_manager_jclouds.JCloudsVirtualFile.isDirectory(JCloudsVirtualFile.java:172)
</span>	at PluginClassLoader <span class="code-keyword">for</span> copyartifact<span class="code-comment">//hudson.plugins.copyartifact.BuildSelector.getArtifacts(BuildSelector.java:131)
</span>	at PluginClassLoader <span class="code-keyword">for</span> copyartifact<span class="code-comment">//hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:673)
</span>	at PluginClassLoader <span class="code-keyword">for</span> copyartifact<span class="code-comment">//hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:563)
</span>	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at PluginClassLoader <span class="code-keyword">for</span> workflow-basic-steps<span class="code-comment">//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
</span>	at PluginClassLoader <span class="code-keyword">for</span> workflow-basic-steps<span class="code-comment">//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
</span>	at PluginClassLoader <span class="code-keyword">for</span> workflow-step-api<span class="code-comment">//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
</span>	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:840) </pre>
</div></div></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
latest Jenkins LTS<br/>
871.v72f7f642a_245 plugin
```
</details>

**Comment by NorseGaud** [comment]
Bump!
